server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lwb_data?characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true  #格式化sql